name: Doxygen Docs

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Doxygen dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz mscgen

      - name: Generate Doxygen
        run: doxygen Doxyfile

      - name: Upload Doxygen artifact
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-html
          path: docs/doxygen_output/html
          retention-days: 7
